name: libman
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  http: ^0.13.5
  image_picker: ^0.8.6
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - image/daftarBuku/
    - image/gambar/
    - image/images/
  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Regular.ttf
          style: italic
